apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: '2022-02-11T19:39:02Z'
  generation: 15
  labels:
    app: landuseplanning
    env: dev
    name: lup-api
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:env': {}
            'f:name': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-02-11T19:39:23Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finally': {}
          'f:tasks': {}
      manager: Mozilla
      operation: Update
      time: '2025-03-21T20:10:27Z'
  name: lup-api-build-deploy-dev
  namespace: e8b9ad-tools
  resourceVersion: '13745680169'
  uid: 5b9acbbe-708b-4b3c-ac33-56abf3ebf0f2
spec:
  finally:
    - name: push-to-teams-success
      params:
        - name: webhook-url
          value: 'https://bcgov.webhook.office.com/webhookb2/85d42a52-f637-43bb-af02-817e93e8cb6f@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/fb6c473cce1c4be49b6b54fc89d3e7c9/2c1af31d-c876-40e0-b2e6-ca14006d7319/V2qzaDPI4OCXq2xUDTmNdOacE3Qwdgo3SATHKcquR8K841'
        - name: webhook-payload
          value: |-
            {
                "@type": "MessageCard",
                "@context": "https://schema.org/extensions",
                "summary": "Issue 176715375",
                "themeColor": "33cc33",
                "title": "[LUP] Land Use Planning API has been deployed to dev",
                "sections": [
                    {
                        "text": "The latest version of Land Use Planning **API** has been built and deployed to **dev**."
                    }
                ],
                "potentialAction": [
                    {
                        "@type": "OpenUri",
                        "name": "View on OpenShift",
                        "targets": [
                            {
                                "os": "default",
                                "uri": "https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e8b9ad-tools/tekton.dev~v1beta1~Pipeline/lup-api-build-deploy-dev/Runs"
                            }
                        ]
                    }
                ]
            }
      taskRef:
        kind: Task
        name: push-to-teams
      when:
        - input: $(tasks.status)
          operator: notin
          values:
            - Failed
    - name: push-to-teams-failure
      params:
        - name: webhook-url
          value: 'https://bcgov.webhook.office.com/webhookb2/85d42a52-f637-43bb-af02-817e93e8cb6f@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/fb6c473cce1c4be49b6b54fc89d3e7c9/2c1af31d-c876-40e0-b2e6-ca14006d7319/V2qzaDPI4OCXq2xUDTmNdOacE3Qwdgo3SATHKcquR8K841'
        - name: webhook-payload
          value: "{\n\t\"@type\": \"MessageCard\",\n\t\"@context\": \"https://schema.org/extensions\",\n\t\"summary\": \"Issue 176715375\",\n\t\"themeColor\": \"cc3333\",\n\t\"title\": \"[FAIL][LUP] Land Use Planning API dev pipeline failed\",\n\t\"sections\": [\n\t\t{\n\t\t\t\"text\": \"There was an issue with the latest **dev** pipeline run for Land Use Planning **API**.\"\n\t\t}\n\t],\n\t\"potentialAction\": [\n\t\t{\n\t\t\t\"@type\": \"OpenUri\",\n\t\t\t\"name\": \"View on OpenShift\",\n\t\t\t\"targets\": [\n\t\t\t\t{\n\t\t\t\t\t\"os\": \"default\",\n\t\t\t\t\t\"uri\": \"https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e8b9ad-tools/tekton.dev~v1beta1~Pipeline/lup-api-build-deploy-dev/Runs\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t]\n}"
      taskRef:
        kind: Task
        name: push-to-teams
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Failed
  tasks:
    - name: build-api
      params:
        - name: SCRIPT
          value: |
            oc start-build landuseplanning-api --follow --wait
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: tag-image
      params:
        - name: SCRIPT
          value: |
            oc tag landuseplanning-api:latest landuseplanning-api:dev
      runAfter:
        - build-api
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: trigger-deployment
      params:
        - name: SCRIPT
          value: |
            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
            oc patch deployment/landuseplanning-api-dev -n e8b9ad-dev --patch "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"last-restart\":\"$TIMESTAMP\"}}}}}"
      runAfter:
        - tag-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
