kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '28'
  name: landuseplanning-api-dev
  namespace: e8b9ad-dev
  labels:
    app: landuseplanning-api-dev
    app.kubernetes.io/component: landuseplanning-api-dev
    app.kubernetes.io/instance: landuseplanning-api-dev
    app.kubernetes.io/part-of: landuseplanning-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landuseplanning-api-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landuseplanning-api-dev
      annotations:
        last-restart: '2025-03-28 22:59:20'
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: landuseplanning-api-dev
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: KEYCLOAK_ENABLED
              value: 'true'
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-name
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-password
            - name: MONGODB_SERVICE_HOST
              value: landuseplanning-api-mongodb-dev
            - name: MINIO_HOST
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-minio-dev
                  key: minio-host
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-minio-dev
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-minio-dev
                  key: minio-secret-key
            - name: CHES_AUTH_ENDPOINT
              value: 'https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
            - name: _EMAIL_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-email-dev
                  key: email-client-id
            - name: _EMAIL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-email-dev
                  key: email-client-secret
            - name: CHES_ENDPOINT
              value: 'https://ches-test.api.gov.bc.ca/'
            - name: SSO_ISSUER
              value: 'https://test.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: SSO_JWKSURI
              value: 'https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs'
            - name: CLAMAV_SERVICE_HOST
              value: lup-clamav.e8b9ad-tools.svc.cluster.local
            - name: CLAMAV_SERVICE_PORT
              value: '3310'
            - name: ENABLE_VIRUS_SCANNING
              value: 'true'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: image-registry.apps.silver.devops.gov.bc.ca/e8b9ad-tools/landuseplanning-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
