kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: landuseplanning-api-mongodb-test
  namespace: e8b9ad-test
  uid: 0ae91a05-b383-4cb6-a883-b5e059695835
  resourceVersion: '12982872881'
  generation: 44
  creationTimestamp: '2021-03-05T16:27:45Z'
  labels:
    app: landuseplanning-api-mongodb-test
    app.kubernetes.io/component: landuseplanning-api-mongodb-test
    app.kubernetes.io/instance: landuseplanning-api-mongodb-test
    app.kubernetes.io/part-of: landuseplanning-api-test
    app.openshift.io/runtime-namespace: openshift
    app.openshift.io/runtime-version: latest
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2021-03-15T17:18:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-namespace': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"landuseplanning-api-mongodb-test"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/var/lib/mongodb/data"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:env':
                    .: {}
                    'k:{"name":"MONGODB_ADMIN_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_DATABASE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_USER"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":27017,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"landuseplanning-api-mongodb-test"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
          'f:triggers': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-03-31T19:59:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2025-01-22T19:33:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: landuseplanning-api-mongodb-test
    deploymentconfig: landuseplanning-api-mongodb-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landuseplanning-api-mongodb-test
        deploymentconfig: landuseplanning-api-mongodb-test
    spec:
      volumes:
        - name: landuseplanning-api-mongodb-test
          persistentVolumeClaim:
            claimName: landuseplanning-api-mongodb-test
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: landuseplanning-api-mongodb-test
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-name
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-admin-password
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: landuseplanning-api-mongodb-test
              mountPath: /var/lib/mongodb/data
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/mongodb'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 44
  details:
    message: manual change
    causes:
      - type: Manual
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 6
  updatedReplicas: 0
  conditions:
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2024-06-27T18:53:09Z'
      lastTransitionTime: '2024-06-27T18:53:09Z'
      reason: ProgressDeadlineExceeded
      message: replication controller "landuseplanning-api-mongodb-test-6" has failed progressing
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-01-22T19:33:54Z'
      lastTransitionTime: '2025-01-22T19:33:54Z'
      message: Deployment config has minimum availability.
  replicas: 1
  readyReplicas: 1
