kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '13334470470'
  name: landuseplanning-api-mongodb-dev
  uid: 5216d7f6-c18a-435b-8f62-b1e627990b71
  creationTimestamp: '2021-02-22T19:56:38Z'
  generation: 17
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2021-02-22T20:52:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-namespace': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"landuseplanning-api-mongodb-dev"}':
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/var/lib/mongodb/data"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:env':
                    .: {}
                    'k:{"name":"MONGODB_ADMIN_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_DATABASE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"MONGODB_USER"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":27017,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"landuseplanning-api-mongodb-dev"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-03-30T19:36:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"landuseplanning-api-mongodb-dev"}':
                  'f:image': {}
          'f:triggers': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2025-02-18T21:28:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: e8b9ad-dev
  labels:
    app: landuseplanning-api-mongodb-dev
    app.kubernetes.io/component: landuseplanning-api-mongodb-dev
    app.kubernetes.io/instance: landuseplanning-api-mongodb-dev
    app.kubernetes.io/part-of: landuseplanning-api-dev
    app.openshift.io/runtime-namespace: openshift
    app.openshift.io/runtime-version: latest
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - landuseplanning-api-mongodb-dev
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'mongodb:latest'
        lastTriggeredImage: 'image-registry.openshift-image-registry.svc:5000/openshift/mongodb@sha256:8dc9932eabd30f2ee4d0b882500c65b48f3c2fbbd85bfd51d0d18410af404a39'
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 10
  test: false
  selector:
    app: landuseplanning-api-mongodb-dev
    deploymentconfig: landuseplanning-api-mongodb-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landuseplanning-api-mongodb-dev
        deploymentconfig: landuseplanning-api-mongodb-dev
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: landuseplanning-api-mongodb-dev
          persistentVolumeClaim:
            claimName: landuseplanning-api-mongodb-dev
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: landuseplanning-api-mongodb-dev
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-name
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-dev
                  key: database-admin-password
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: landuseplanning-api-mongodb-dev
              mountPath: /var/lib/mongodb/data
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/mongodb@sha256:8dc9932eabd30f2ee4d0b882500c65b48f3c2fbbd85bfd51d0d18410af404a39'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 6
  observedGeneration: 17
  replicas: 0
  updatedReplicas: 0
  availableReplicas: 0
  unavailableReplicas: 0
  details:
    message: manual change
    causes:
      - type: Manual
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-03-13T00:38:09Z'
      lastTransitionTime: '2024-03-13T00:38:09Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "landuseplanning-api-mongodb-dev-6" successfully rolled out
    - type: Available
      status: 'False'
      lastUpdateTime: '2025-02-18T19:38:15Z'
      lastTransitionTime: '2025-02-18T19:38:15Z'
      message: Deployment config does not have minimum availability.
