 module.exports = require ('../models')('Project', {

    //Needed for default view
    CEAAInvolvement         : { type: String, default: '' },
    CELead                  : { type: String, default: '' },
    CELeadEmail             : { type: String, default: '' },
    CELeadPhone             : { type: String, default: '' },
    centroid                : [{ type: Number, default: 0.00}],
    description             : { type: String, default: '' },
    eacDecision             : { type: String, default: '' },
    location                : { type: String, default: '' },
    name                    : { type: String, trim: true },
    projectLead             : { type: String, default: '' },
    projectLeadEmail        : { type: String, default: '' },
    projectLeadPhone        : { type: String, default: '' },
    proponent               : { type: String, default: '' },
    region                  : { type: String, default: '' },
    responsibleEPD          : { type: String, default: '' },
    responsibleEPDEmail     : { type: String, default: '' },
    responsibleEPDPhone     : { type: String, default: '' },
    type                    : { type: String, default: '' },

    //Everything else
    addedBy                 : { type: String, default: '' },
    build                   : { type: String, default: '' },
    CEAALink                : { type: String, default: '' },
    code                    : { type: String, default: '' },
    commodity               : { type: String, default: '' },
    currentPhaseName        : { type: String, default: '' },
    dateAdded               : { type: String, default: '' },
    dateCommentsClosed      : { type: String, default: '' },
    dateCommentsOpen        : { type: String, default: '' },
    dateUpdated             : { type: String, default: '' },
    decisionDate            : { type: String, default: '' },
    duration                : { type: String, default: '' },
    // TODO: directoryStructure
    eaoMember               : { type: String, default: '' },
    epicProjectID           : { type: Number, default: '' },
    fedElecDist             : { type: String, default: '' },
    // TODO: intake
    isTermsAgreed           : { type: Boolean, default: false },
    overallProgress         : { type: Number },
    primaryContact          : { type: String, default: '' },
    proMember               : { type: String, default: '' },
    provElecDist            : { type: String, default: '' },
    sector                  : { type: String, default: '' },
    shortName               : { type: String, default: '', index: true },
    status                  : { type: String, default: '' },
    substitution            : { type: Boolean, default: false },

    // Permissions
    read                    : [{ type: String, trim: true, default: '["project-system-admin"]' }],
    write                   : [{ type: String, trim: true, default: '["project-system-admin"]' }],
    delete                  : [{ type: String, trim: true, default: '["project-system-admin"]' }],
}, 'epic');
