 module.exports = require ('../models')('Project', {
    cEAAInvolvement     : { type:String, default: '' },
    cELead              : { type:String, default: '' },
    cELeadEmail         : { type:String, default: '' },
    cELeadPhone         : { type:String, default: '' },
    centroid            : [{ type: Number, default: 0.00}],
    currentPhase        : { type:'ObjectId', ref:'Phases', default:null },
    currentPhaseCode    : { type:String, default: '' },
    currentPhaseName    : { type:String, default: '' },
    description         : { type:String, default: '' },
    eacDecision         : { type:String, default: '' },
    location            : { type: String, default: '' },
    name                : { type: String, trim: true },
    projectLead         : { type:String, default: '' },
    projectLeadEmail    : { type:String, default: '' },
    projectLeadPhone    : { type:String, default: '' },
    proponent           : { type:'ObjectId', ref:'Organization', default:null },
    region              : { type:String, default: '' },
    responsibleEPD      : { type:String, default: '' },
    responsibleEPDEmail : { type:String, default: '' },
    responsibleEPDPhone : { type:String, default: '' },
    subtype             : { type: String },
    type                : { type:String, default: '' },
    read                : [[{ type: String, trim: true, default: '[["project-system-admin"]]' }]],
});
