kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  resourceVersion: '13794784226'
  name: el-github-listener
  uid: 35a06857-d4e0-4938-a2f6-06f33ce99c39
  creationTimestamp: '2025-03-21T22:24:23Z'
  generation: 2
  managedFields:
    - manager: openshift-pipelines-triggers-controller
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-25T17:35:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/part-of': {}
            'f:eventlistener': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"a9503ae9-075d-4ef1-b4b5-043ff0d4e5be"}': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app.kubernetes.io/managed-by': {}
                'f:app.kubernetes.io/part-of': {}
                'f:eventlistener': {}
            'f:spec':
              'f:containers':
                'k:{"name":"event-listener"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:args': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"EL_EVENT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"METRICS_PROMETHEUS_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"K_SINK_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SYSTEM_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef': {}
                    'k:{"name":"K_METRICS_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"K_TRACING_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"K_LOGGING_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                    'f:readOnlyRootFilesystem': {}
                    'f:runAsNonRoot': {}
                    'f:seccompProfile':
                      .: {}
                      'f:type': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":9000,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext':
                .: {}
                'f:runAsNonRoot': {}
                'f:seccompProfile':
                  .: {}
                  'f:type': {}
              'f:serviceAccount': {}
              'f:serviceAccountName': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-03-25T17:42:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: e8b9ad-tools
  ownerReferences:
    - apiVersion: triggers.tekton.dev/v1beta1
      kind: EventListener
      name: github-listener
      uid: a9503ae9-075d-4ef1-b4b5-043ff0d4e5be
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: EventListener
      app.kubernetes.io/part-of: Triggers
      eventlistener: github-listener
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: EventListener
        app.kubernetes.io/part-of: Triggers
        eventlistener: github-listener
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: event-listener
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: K_LOGGING_CONFIG
              value: '{"zap-logger-config":"{\n  \"level\": \"info\",\n  \"development\": false,\n  \"disableStacktrace\": true,\n  \"sampling\": {\n    \"initial\": 100,\n    \"thereafter\": 100\n  },\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\": \"json\",\n  \"encoderConfig\": {\n    \"timeKey\": \"timestamp\",\n    \"levelKey\": \"severity\",\n    \"nameKey\": \"logger\",\n    \"callerKey\": \"caller\",\n    \"messageKey\": \"message\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\": \"\",\n    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"iso8601\",\n    \"durationEncoder\": \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"}'
            - name: K_METRICS_CONFIG
              value: '{"Domain":"tekton.dev/triggers","Component":"eventlistener","PrometheusPort":0,"PrometheusHost":"","ConfigMap":{}}'
            - name: K_TRACING_CONFIG
              value: '{"backend":"none","debug":"false","sample-rate":"0.1"}'
            - name: NAMESPACE
              value: e8b9ad-tools
            - name: NAME
              value: github-listener
            - name: EL_EVENT
              value: enable
            - name: K_SINK_TIMEOUT
              value: '30'
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: METRICS_PROMETHEUS_PORT
              value: '9000'
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'registry.redhat.io/openshift-pipelines/pipelines-triggers-eventlistenersink-rhel8@sha256:867548e7c74f8ff455454b3208d0bad679c144c0d12f187cf054260333b032cd'
          args:
            - '--el-name=github-listener'
            - '--el-namespace=e8b9ad-tools'
            - '--port=8080'
            - '--readtimeout=5'
            - '--writetimeout=40'
            - '--idletimeout=120'
            - '--timeouthandler=30'
            - '--httpclient-readtimeout=30'
            - '--httpclient-keep-alive=30'
            - '--httpclient-tlshandshaketimeout=10'
            - '--httpclient-responseheadertimeout=10'
            - '--httpclient-expectcontinuetimeout=1'
            - '--is-multi-ns=false'
            - '--payload-validation=true'
            - '--cloudevent-uri='
            - '--tls-cert='
            - '--tls-key='
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: pipeline
      serviceAccount: pipeline
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-03-25T17:42:53Z'
      lastTransitionTime: '2025-03-25T17:42:53Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-03-25T17:42:53Z'
      lastTransitionTime: '2025-03-21T22:24:23Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "el-github-listener-8585f9ccfd" has successfully progressed.
