kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: landuseplanning-api-mongodb-prod
  namespace: e8b9ad-prod
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pvc-4755190f-3bc8-4b37-9dcc-f0caf3304d69
  storageClassName: netapp-file-standard
  volumeMode: Filesystem