kind: Deployment
apiVersion: apps/v1
metadata:
  name: landuseplanning-api-mongodb-test
  namespace: e8b9ad-test
  labels:
    app: landuseplanning-api-mongodb-test
    app.kubernetes.io/component: landuseplanning-api-mongodb-test
    app.kubernetes.io/instance: landuseplanning-api-mongodb-test
    app.kubernetes.io/part-of: landuseplanning-api-test
    app.openshift.io/runtime-namespace: openshift
    app.openshift.io/runtime-version: latest
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: landuseplanning-api-mongodb-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landuseplanning-api-mongodb-test
    spec:
      volumes:
        - name: landuseplanning-api-mongodb-test
          persistentVolumeClaim:
            claimName: landuseplanning-api-mongodb-test
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: landuseplanning-api-mongodb-test
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-name
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landuseplanning-api-mongodb-test
                  key: database-admin-password
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: landuseplanning-api-mongodb-test
              mountPath: /var/lib/mongodb/data
          terminationMessagePolicy: File
          image: 'image-registry.apps.silver.devops.gov.bc.ca/openshift/mongodb'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
