kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: landuseplanning-api-mongodb-test
  namespace: e8b9ad-test
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: pvc-3c064955-95b1-41fb-85d6-fa21f15fb7a2
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
