name: Lint and Test API Backend
on:
  pull_request:
    branches:
      - dev
    paths:
      - "api/controllers/*.js"
      - "api/helpers/**/*.js"
      - "api/test/*.js"
      - "api/test/**/*.js"
      - "app.js"

jobs:
  static_checks:
    if: ${{ github.repository_owner == 'bcgov' && github.event.pull_request.draft == false }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
